package cn.edu.nxu.it.model;

import cn.edu.nxu.it.model.base.BaseCast;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cast extends BaseCast<Cast> {
	public static final Cast dao = new Cast().dao();
}
