package cn.edu.nxu.it.model;

import cn.edu.nxu.it.model.base.BaseCastRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CastRole extends BaseCastRole<CastRole> {
	public static final CastRole dao = new CastRole().dao();
}
