package cn.edu.nxu.it.model;

import cn.edu.nxu.it.model.base.BaseCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Course extends BaseCourse<Course> {
	public static final Course dao = new Course().dao();
}
