package cn.edu.nxu.it.model;

import cn.edu.nxu.it.model.base.BaseGenre;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Genre extends BaseGenre<Genre> {
	public static final Genre dao = new Genre().dao();
}
