package cn.edu.nxu.it.model;

import cn.edu.nxu.it.model.base.BaseMovieGenre;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MovieGenre extends BaseMovieGenre<MovieGenre> {
	public static final MovieGenre dao = new MovieGenre().dao();
}
