package cn.edu.nxu.it.model;

import cn.edu.nxu.it.model.base.BaseMovieCast;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MovieCast extends BaseMovieCast<MovieCast> {
	public static final MovieCast dao = new MovieCast().dao();
}
