package cn.edu.nxu.it.model;

import cn.edu.nxu.it.model.base.BaseScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Score extends BaseScore<Score> {
	public static final Score dao = new Score().dao();
}
