package cn.edu.nxu.it.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public M setCno(java.lang.String cno) {
		set("cno", cno);
		return (M)this;
	}


	public java.lang.String getCno() {
		return getStr("cno");
	}


	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}


	public java.lang.String getName() {
		return getStr("name");
	}


	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}


	public java.lang.String getComment() {
		return getStr("comment");
	}


}
