package cn.edu.nxu.it.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMovie<M extends BaseMovie<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setOriginalTitle(java.lang.String originalTitle) {
		set("original_title", originalTitle);
		return (M)this;
	}


	public java.lang.String getOriginalTitle() {
		return getStr("original_title");
	}


	public M setChineseTitle(java.lang.String chineseTitle) {
		set("chinese_title", chineseTitle);
		return (M)this;
	}


	public java.lang.String getChineseTitle() {
		return getStr("chinese_title");
	}


	public M setAka(java.lang.String aka) {
		set("aka", aka);
		return (M)this;
	}


	public java.lang.String getAka() {
		return getStr("aka");
	}


	public M setYear(java.lang.String year) {
		set("year", year);
		return (M)this;
	}


	public java.lang.String getYear() {
		return getStr("year");
	}


	public M setRegion(java.lang.String region) {
		set("region", region);
		return (M)this;
	}


	public java.lang.String getRegion() {
		return getStr("region");
	}


	public M setDuration(java.lang.Double duration) {
		set("duration", duration);
		return (M)this;
	}


	public java.lang.Double getDuration() {
		return getDouble("duration");
	}


	public M setLanguage(java.lang.String language) {
		set("language", language);
		return (M)this;
	}


	public java.lang.String getLanguage() {
		return getStr("language");
	}


	public M setPubDate(java.util.Date pubDate) {
		set("pub_date", pubDate);
		return (M)this;
	}


	public java.util.Date getPubDate() {
		return get("pub_date");
	}


	public M setPoster(java.lang.String poster) {
		set("poster", poster);
		return (M)this;
	}


	public java.lang.String getPoster() {
		return getStr("poster");
	}


	public M setSummary(java.lang.String summary) {
		set("summary", summary);
		return (M)this;
	}


	public java.lang.String getSummary() {
		return getStr("summary");
	}


	public M setDoubanId(java.lang.Double doubanId) {
		set("douban_id", doubanId);
		return (M)this;
	}


	public java.lang.Double getDoubanId() {
		return getDouble("douban_id");
	}


	public M setRating(java.lang.Double rating) {
		set("rating", rating);
		return (M)this;
	}


	public java.lang.Double getRating() {
		return getDouble("rating");
	}


	public M setPosterUrl(java.lang.String posterUrl) {
		set("poster_url", posterUrl);
		return (M)this;
	}


	public java.lang.String getPosterUrl() {
		return getStr("poster_url");
	}


}
