package cn.edu.nxu.it.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMovieGenre<M extends BaseMovieGenre<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setMovieId(java.lang.Integer movieId) {
		set("movie_id", movieId);
		return (M)this;
	}


	public java.lang.Integer getMovieId() {
		return getInt("movie_id");
	}


	public M setGenreId(java.lang.Integer genreId) {
		set("genre_id", genreId);
		return (M)this;
	}


	public java.lang.Integer getGenreId() {
		return getInt("genre_id");
	}


}
