package cn.edu.nxu.it.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMovieCast<M extends BaseMovieCast<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setMovieId(java.lang.Integer movieId) {
		set("movie_id", movieId);
		return (M)this;
	}


	public java.lang.Integer getMovieId() {
		return getInt("movie_id");
	}


	public M setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}


	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}


	public M setCastId(java.lang.Integer castId) {
		set("cast_id", castId);
		return (M)this;
	}


	public java.lang.Integer getCastId() {
		return getInt("cast_id");
	}


	public M setActAs(java.lang.String actAs) {
		set("act_as", actAs);
		return (M)this;
	}


	public java.lang.String getActAs() {
		return getStr("act_as");
	}


}
