package cn.edu.nxu.it.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCast<M extends BaseCast<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setChineseName(java.lang.String chineseName) {
		set("chinese_name", chineseName);
		return (M)this;
	}


	public java.lang.String getChineseName() {
		return getStr("chinese_name");
	}


	public M setEnglishName(java.lang.String englishName) {
		set("english_name", englishName);
		return (M)this;
	}


	public java.lang.String getEnglishName() {
		return getStr("english_name");
	}


	public M setGender(java.lang.String gender) {
		set("gender", gender);
		return (M)this;
	}


	public java.lang.String getGender() {
		return getStr("gender");
	}


	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}


	public java.lang.String getAvatar() {
		return getStr("avatar");
	}


	public M setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}


	public java.util.Date getBirthday() {
		return get("birthday");
	}


	public M setRegion(java.lang.String region) {
		set("region", region);
		return (M)this;
	}


	public java.lang.String getRegion() {
		return getStr("region");
	}


	public M setSummary(java.lang.String summary) {
		set("summary", summary);
		return (M)this;
	}


	public java.lang.String getSummary() {
		return getStr("summary");
	}


	public M setDoubanId(java.lang.Integer doubanId) {
		set("douban_id", doubanId);
		return (M)this;
	}


	public java.lang.Integer getDoubanId() {
		return getInt("douban_id");
	}


	public M setAvatarUrl(java.lang.String avatarUrl) {
		set("avatar_url", avatarUrl);
		return (M)this;
	}


	public java.lang.String getAvatarUrl() {
		return getStr("avatar_url");
	}


	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}


	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}


}
