package cn.edu.nxu.it.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}


	public java.lang.String getUsername() {
		return getStr("username");
	}


	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}


	public java.lang.String getPassword() {
		return getStr("password");
	}


	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}


	public java.lang.String getEmail() {
		return getStr("email");
	}


	public M setHeadUrl(java.lang.String headUrl) {
		set("head_url", headUrl);
		return (M)this;
	}


	public java.lang.String getHeadUrl() {
		return getStr("head_url");
	}


	public M setGender(java.lang.Boolean gender) {
		set("gender", gender);
		return (M)this;
	}


	public java.lang.Boolean isGender() {
		return get("gender");
	}


	public M setStatus(java.lang.Boolean status) {
		set("status", status);
		return (M)this;
	}


	public java.lang.Boolean isStatus() {
		return get("status");
	}


	public M setAdmin(java.lang.Boolean admin) {
		set("admin", admin);
		return (M)this;
	}


	public java.lang.Boolean isAdmin() {
		return get("admin");
	}


	public M setRole(java.lang.Boolean role) {
		set("role", role);
		return (M)this;
	}


	public java.lang.Boolean isRole() {
		return get("role");
	}


}
