package cn.edu.nxu.it.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCastRole<M extends BaseCastRole<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}


	public java.lang.String getName() {
		return getStr("name");
	}


	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}


	public java.lang.String getRemark() {
		return getStr("remark");
	}


}
